export const INVALID_SESSION_ID_FORMAT = 80001;
export const SESSION_ID_NOT_GENERATED = 80002;
export const NO_SESSION_ID_FOR_NEW_REQUEST_TRUE = 80003;
export const SESSION_ID_TYPE_ERROR = 80004;
export const INVALID_SESSION_ID_COOKIE = 80005;

export const NO_SESSION_ID_IN_REQUEST = 80101;
export const NO_SESSION_DATA_FROM_STORE = 80102;
export const NO_SESSION_ID_ON_SESSION = 80103;

export const NEW_SESSION_ID_DATA_EXISTS = 80201;
export const ERROR_RETRIEVING_SESSION_DATA = 80202;
export const ERROR_SESSION_NOT_INITIALIZED = 80203;
export const PREREQUISITE_HANDLER_NOT_CALLED = 80204;
export const ERROR_SAVING_SESSION = 80205;
export const ERROR_AUTHENTICATING_USER = 80206;
export const ERROR_SESSION_VALUES_MISSING = 80207;
export const SESSION_REGENERATION_ERROR = 80208;

// HTTP 500 Errors
export const REQUIRED_MIDDLEWARE_NOT_CALLED = 80301;
export const SESSION_STORE_NOT_CONFIGURED = 80302;
export const SESSION_ID_DATA_MISMATCH = 80303;
export const REQUIRED_MIDDLEWARE_CALLED_INCORRECTLY = 80304;
export const ERROR_SESSION_ID_WITH_NO_DATA = 80305;
export const ERROR_SESSION_ID_NOT_GENERATED = 80306;
export const SESSION_ID_GENERATION_ERROR = 80307;
export const SESSION_ID_MISMATCH_ERROR = 80308;
export const ERROR_REQUEST_SESSION_NOT_INITIALIZED = 80309;
export const LOGOUT_FAILED_ERROR = 80310;
export const ERROR_MIDDLEWARE_PREREQUISITE_NOT_MET = 80311;

export const USER_INPUT_VALIDATION_ERROR = 80401;
export const USER_INPUT_EMAIL_VALIDATION_ERROR = 80402;
export const USER_AUTHENTICATION_ERROR = 80403;
