name: Update dependency
run-name: Update the npm dependency for ${{ inputs.package == 'other' && inputs.free-package || inputs.package }}
on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: 'Dependency to update'
        required: true
        default: 'other'
        options:
        - 'other'
        - '@tjsr/mysql-pool-utils'
        - '@tjsr/simple-env-utils'
        - '@tjsr/testutils'
        - '@types/node'
        - 'typescript'
        - 'vitest'
      free-package:
        type: string
        description: 'Free-form package name to update (optional)'
        required: false
      package-version:
        description: 'Package version to use (optional)'
        type: string
        required: false
  workflow_call:
    inputs:
      package:
        type: string
        required: true
      package-version:
        type: string
        required: false
  
jobs:
  create-branch:
    permissions:
      contents: write
      pull-requests: write
      packages: read

    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PROJECT: tagtool
      PACKAGE: ${{ inputs.package == 'other' && inputs.free-package || inputs.package }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Check latest version and create PR
        id: raise-version-pr
        uses: tjsr/gh-util-actions/npm-dependency-pr@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dependency: ${{ env.PACKAGE }}
          packageVersion: ${{ inputs.package-version }}
          reviewers: 'tjsr'

      - name: Verify PR creation details (skipped if no PR was created)
        id: pr-details
        if: steps.raise-version-pr.outputs.pullRequestNumber
        run: |
          echo "PR ${{ steps.raise-version-pr.outputs.pullRequestNumber }} crated at ${{ steps.raise-version-pr.outputs.pullRequestUrl }}"

