name: Fire webhooks to dependent repositories when published
run-name: ${{ github.actor }} Update an npm dependency when published
on:
  registry_package:
    types: [published]
  workflow_dispatch:
  push: 
    branches:
      - workflow/published.yml

env:
  repo_owner: tjsr

jobs:
  fire-tagtool-update:
    name: Fire webhook to check dependency updates on tagtool
    runs-on: ubuntu-latest
    env:
      repo_name: tagtool
    steps:
      - name: Fire webhook to dependency update
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ${{ env.repo_owner }}
          github_token: ${{ secrets.BUILD_WEBHOOK_TOKEN }}
          workflow_file_name: dependency.yml
          ref: main
          repo: ${{ env.repo_name }}
          client_payload: '{"package": "@tjsr/user-session-middleware"}'
          propagate_failure: true
          wait_workflow: true

        # run: |
        #   curl -L \
        #     -X POST \
        #     -H "Content-Type: application/json" \
        #     https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
        #     -d '{"event_type": "trigger_workflow", "client_payload": \
        #       {"package": "@tjsr/user-session-middleware"}'

